version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8069:8069"
    links:
      - "db:postgres"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./postgres-data:/var/lib/postgresql

volumes:
     postgres-data: